ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView


urlpatterns = ([
    path('admin/', admin.site.urls),
    path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('', include("web.urls", namespace='web')),
    path('main/', include('main.urls', namespace='main')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('products/', include('products.urls', namespace='products')),
]
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

main/urls.py
from django.urls import path


app_name = "main"

urlpatterns = [
  
]

orders/urls.py
from django.urls import path


app_name = "orders"

urlpatterns = [
  
]

products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [

    path('list/category',views.CategoryListView.as_view(), name='list_category'),
    path('list/sub_category',views.SubCategoryListView.as_view(), name='list_sub_category'),
    path('list/product',views.ProductListView.as_view(), name='list_product'),
]

web/urls.py
from django.urls import path
from . import views

app_name = "web"

urlpatterns = [
        path("", views.HomeView.as_view(), name="home")
]

main/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from versatileimagefield.fields import VersatileImageField,PPOIField

class Category(models.Model):
    category_name = models.CharField(max_length=128)
    category_image = VersatileImageField('Category Image',upload_to="category/")
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ['category_name']

    def __str__(self):
        return self.category_name

class SubCategory(models.Model):
    parent_category =models.ForeignKey('products.Category', on_delete=models.PROTECT)
    sub_category_name = models.CharField(max_length=128)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'Sub Category'
        verbose_name_plural = 'Sub Categories'
        ordering = ['parent_category','sub_category_name']

    def __str__(self):
        return f"{self.sub_category_name} {self.parent_category} "
    
class Product(models.Model):
    sub_category = models.ForeignKey('products.SubCategory',on_delete=models.PROTECT)
    product_name = models.CharField(max_length=100)
    price =models.DecimalField(max_digits=10, decimal_places=2)
    product_image1 = VersatileImageField('Product_Image1',upload_to="products/")
    ppoi = PPOIField("Product_Image1 PPOI")
    product_image2 = VersatileImageField('Product_Image2',upload_to="products/")
    ppoi = PPOIField("Product_Image2 PPOI")
    product_description = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['sub_category','product_name']

    def __str__(self):
        return self.product_name

class ProductVariant(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='product_variants')
    variant_name = models.CharField(max_length=150)
    variant_description = models.TextField(null=True, blank=True)

class ProductImage(models.Model):
    product_varient = models.ForeignKey(ProductVariant, on_delete=models.PROTECT, related_name='product_images')
    product_image = VersatileImageField('Product_Image',upload_to="category/")
    ppoi = PPOIField("Product_Image PPOI")

web/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

# Create your views here.

orders/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.shortcuts import render
from django.views.generic import ListView

from products.models import Category, Product, SubCategory


class CategoryListView(ListView):
    model = Category

class SubCategoryListView(ListView):
    model = SubCategory

class ProductListView(ListView):
    model = Product

web/views.py
from typing import Any
from django.shortcuts import render
from django.views.generic import ListView
from products.models import Product,Category

class HomeView(ListView):
    model = Product
    template_name = "web/index.html"
    context_object_name = "products"

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['is_index'] = True
        context['categories'] = Category.objects.all()
        return context

templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="description" content="description">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Title Of Site -->
        <title>Ecommerce</title>
        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'web/assets/images/favicon.png' %}" />
        <!-- Plugins CSS -->
        <link rel="stylesheet" href="{% static 'web/assets/css/plugins.css' %}">
        <!-- Main Style CSS -->
        <link rel="stylesheet" href="{% static 'web/assets/css/style-min.css' %}">
        <link rel="stylesheet" href="{% static 'web/assets/css/responsive.css' %}">
    </head>

    <body class="template-index index-demo1">
        <!--Page Wrapper-->
        <div class="page-wrapper">
            
            {% include 'web/partials/top-bar-slider.html' %}


           {% include 'web/partials/header.html' %}

            {% include 'web/partials/mobile-menu.html' %}

            <!-- Body Container -->
            <div id="page-content" class="mb-0">
                
                {% block content %} {% endblock content %}
               

              
            </div>
            <!-- End Body Container -->

            {% include 'web/partials/mini-cart.html' %}
           {% include 'web/partials/footer.html' %}

            
          

            <!--Scoll Top-->
            <div id="site-scroll"><i class="icon anm anm-arw-up"></i></div>
            <!--End Scoll Top-->


            

            


          

        </div>
        <!--End Page Wrapper-->

          <!-- Including Jquery/Javascript -->
            <!-- Plugins JS -->
            <script src="{% static 'web/assets/js/plugins.js' %}"></script>
            <!-- Main JS -->
            <script src="{% static 'web/assets/js/main.js' %}"></script>
    </body>
</html>

templates/products/category_list.html
{% load static %}

<!--Popular Categories-->
<section class="section collection-slider pb-0">
    <div class="container">
        <div class="section-header">
            <p class="mb-2 mt-0">Shop by category</p>
            <h2>Popular Collections</h2>
        </div>

        <div class="collection-slider-5items gp15 arwOut5 hov-arrow">
            <div class="category-item zoomscal-hov">
                <a href="shop-left-sidebar.html" class="category-link clr-none">
                    <div class="zoom-scal zoom-scal-nopb rounded-3"><img class="blur-up lazyload" data-src="{% static 'web/assets/images/collection/sub-collection1.jpg' %}" src="{% static 'web/assets/images/collection/sub-collection1.jpg' %}" alt="Men's Jakets" title="Men's Jakets" width="365" height="365" /></div>
                    <div class="details mt-3 text-center">
                        <h4 class="category-title mb-0">Men's Jakets</h4>
                        <p class="counts">20 Products</p>
                    </div>
                </a>
            </div>
            <div class="category-item zoomscal-hov">
                <a href="shop-left-sidebar.html" class="category-link clr-none">
                    <div class="zoom-scal zoom-scal-nopb rounded-3"><img class="blur-up lazyload" data-src="{% static 'web/assets/images/collection/sub-collection3.jpg' %}" src="{% static 'web/assets/images/collection/sub-collection3.jpg' %}" alt="Tops" title="Tops" width="365" height="365" /></div>
                    <div class="details mt-3 text-center">
                        <h4 class="category-title mb-0">Tops</h4>
                        <p class="counts">13 Products</p>
                    </div>
                </a>
            </div>
            <div class="category-item zoomscal-hov">
                <a href="shop-left-sidebar.html" class="category-link clr-none">
                    <div class="zoom-scal zoom-scal-nopb rounded-3"><img class="blur-up lazyload" data-src="{% static 'web/assets/images/collection/sub-collection5.jpg' %}" src="{% static 'web/assets/images/collection/sub-collection5.jpg' %}" alt="T-Shirts" title="T-Shirts" width="365" height="365" /></div>
                    <div class="details mt-3 text-center">
                        <h4 class="category-title mb-0">T-Shirts</h4>
                        <p class="counts">18 Products</p>
                    </div>
                </a>
            </div>
            <div class="category-item zoomscal-hov">
                <a href="shop-left-sidebar.html" class="category-link clr-none">
                    <div class="zoom-scal zoom-scal-nopb rounded-3"><img class="blur-up lazyload" data-src="{% static 'web/assets/images/collection/sub-collection6.jpg' %}" src="{% static 'web/assets/images/collection/sub-collection6.jpg' %}" alt="Shoes" title="Shoes" width="365" height="365" /></div>
                    <div class="details mt-3 text-center">
                        <h4 class="category-title mb-0">Shoes</h4>
                        <p class="counts">11 Products</p>
                    </div>
                </a>
            </div>
            <div class="category-item zoomscal-hov">
                <a href="shop-left-sidebar.html" class="category-link clr-none">
                    <div class="zoom-scal zoom-scal-nopb rounded-3"><img class="blur-up lazyload" data-src="{% static 'web/assets/images/collection/sub-collection9.jpg' %}" src="{% static 'web/assets/images/collection/sub-collection9.jpg' %}" alt="Shorts" title="Shorts" width="365" height="365"/></div>
                    <div class="details mt-3 text-center">
                        <h4 class="category-title mb-0">Shorts</h4>
                        <p class="counts">28 Products</p>
                    </div>
                </a>
            </div>
            <div class="category-item zoomscal-hov">
                <a href="shop-left-sidebar.html" class="category-link clr-none">
                    <div class="zoom-scal zoom-scal-nopb rounded-3"><img class="blur-up lazyload" data-src="{% static 'web/assets/images/collection/sub-collection2.jpg' %}" src="{% static 'web/assets/images/collection/sub-collection2.jpg' %}" alt="Sunglasses" title="Sunglasses" width="365" height="365" /></div>
                    <div class="details mt-3 text-center">
                        <h4 class="category-title mb-0">Sunglasses</h4>
                        <p class="counts">24 Products</p>
                    </div>
                </a>
            </div>
            <div class="category-item zoomscal-hov">
                <a href="shop-left-sidebar.html" class="category-link clr-none">
                    <div class="zoom-scal zoom-scal-nopb rounded-3"><img class="blur-up lazyload" data-src="{% static 'web/assets/images/collection/sub-collection4.jpg' %}" src="{% static 'web/assets/images/collection/sub-collection4.jpg' %}" alt="Girls Top" title="Girls Top" width="365" height="365" /></div>
                    <div class="details mt-3 text-center">
                        <h4 class="category-title mb-0">Girls Top</h4>
                        <p class="counts">26 Products</p>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>
<!--End Popular Categories-->

templates/products/main-category.html
{% load static %}

<!--Collection banner-->
<section class="section collection-banners pb-0">
    <div class="container">                      
        <div class="collection-banner-grid">
            <div class="row sp-row">
                <div class="col-12 col-sm-6 col-md-6 col-lg-6 collection-banner-item">
                    <div class="collection-item sp-col">
                        <a href="shop-left-sidebar.html" class="zoom-scal">
                            <div class="img">
                                <img class="blur-up lazyload" data-src="{% static 'web/assets/images/collection/demo1-ct-img1.jpg' %}" src="{% static 'web/assets/images/collection/demo1-ct-img1.jpg' %}" alt="Women Wear" title="Women Wear" width="645" height="723" />
                            </div>
                            <div class="details middle-right">
                                <div class="inner">
                                    <p class="mb-2">Trending Now</p>
                                    <h3 class="title">Women Wear</h3>
                                    <span class="btn btn-outline-secondary btn-md">Shop Now</span>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-12 col-sm-6 col-md-6 col-lg-6 collection-banner-item">
                    <div class="collection-item sp-col">
                        <a href="shop-left-sidebar.html" class="zoom-scal">
                            <div class="img">
                                <img class="blur-up lazyload" data-src="{% static 'web/assets/images/collection/demo1-ct-img2.jpg' %}" src="{% static 'web/assets/images/collection/demo1-ct-img2.jpg' %}" alt="Mens Wear" title="Mens Wear" width="645" height="344" />
                            </div>
                            <div class="details middle-left">
                                <div class="inner">
                                    <h3 class="title mb-2">Mens Wear</h3>
                                    <p class="mb-3">Tailor-made with passion</p>
                                    <span class="btn btn-outline-secondary btn-md">Shop Now</span>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="collection-item sp-col">
                        <a href="shop-left-sidebar.html" class="zoom-scal">
                            <div class="img">
                                <img class="blur-up lazyload" data-src="{% static 'web/assets/images/collection/demo1-ct-img3.jpg' %}" src="{% static 'web/assets/images/collection/demo1-ct-img3.jpg' %}" alt="Kids Wear" title="Kids Wear" width="645" height="349" />
                            </div>
                            <div class="details middle-right">
                                <div class="inner">
                                    <p class="mb-2">Buy one get one free</p>
                                    <h3 class="title">Kids Wear</h3>
                                    <span class="btn btn-outline-secondary btn-md">Shop Now</span>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--End Collection banner-->

templates/products/subcategory_list.html
{% extends 'base.html' %}

{% block content %}
<ol>
    {% for category in object_list %}
    <li>{{ category }}</li>
    {% endfor %}
</ol>
{% endblock content %}

templates/web/index.html
{% extends 'base.html' %}

{% block content %} 
{% include 'web/partials/banner.html' %}

{% include 'products/main-category.html' %}

{% include 'products/category_list.html' %}

{% include 'products/product_list.html' %}

{% endblock content %}

templates/web/partials/banner.html
{% load static %}

<!--Home Slideshow-->
<section class="slideshow slideshow-wrapper">
    <div class="home-slideshow slick-arrow-dots">
        <div class="slide">
            <div class="slideshow-wrap">
                <picture>
                    <source media="(max-width:767px)" srcset="{% static 'web/assets/images/slideshow/demo1-banner1-mbl.jpg' %}" width="1150" height="800">
                    <img class="blur-up lazyload" src="{% static 'web/assets/images/slideshow/demo1-banner1.jpg' %}" alt="slideshow" title="" width="1920" height="795" />
                </picture> 
                <div class="container">
                    <div class="slideshow-content slideshow-overlay middle-left">
                        <div class="slideshow-content-in">
                            <div class="wrap-caption animation style1">
                                <p class="ss-small-title">Elegant design</p>
                                <h2 class="ss-mega-title">Making someone feel <br>pretty is an art</h2>
                                <p class="ss-sub-title xs-hide">Perfectly designed to ensures ultimate comfort and style</p>
                                <div class="ss-btnWrap">
                                    <a class="btn btn-primary" href="shop-grid-view.html">Shop Women</a>
                                    <a class="btn btn-secondary" href="shop-grid-view.html">Shop Men</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="slide">
            <div class="slideshow-wrap">
                <picture>
                    <source media="(max-width:767px)" srcset="{% static 'web/assets/images/slideshow/demo1-banner2-mbl.jpg' %}" width="1150" height="800">
                    <img class="blur-up lazyload" src="{% static 'web/assets/images/slideshow/demo1-banner2.jpg' %}" alt="slideshow" title="" width="1920" height="795" />
                </picture>  
                <div class="container">
                    <div class="slideshow-content slideshow-overlay middle-right">
                        <div class="slideshow-content-in">
                            <div class="wrap-caption animation style1">
                                <h2 class="ss-mega-title">Spread Positive <br>Energy With Hema</h2>
                                <p class="ss-sub-title xs-hide">The must-have closet essential women wardrobe for the year</p>
                                <div class="ss-btnWrap d-flex-justify-start">
                                    <a class="btn btn-primary" href="shop-grid-view.html">Explore Now!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="slide">
            <div class="slideshow-wrap">
                <picture>
                    <source media="(max-width:767px)" srcset="{% static 'web/assets/images/slideshow/demo1-banner3-mbl.jpg' %}" width="1150" height="800">
                    <img class="blur-up lazyload" src="{% static 'web/assets/images/slideshow/demo1-banner3.jpg' %}" alt="slideshow" title="" width="1920" height="795" />
                </picture>  
                <div class="container">
                    <div class="slideshow-content slideshow-overlay middle-right">
                        <div class="slideshow-content-in">
                            <div class="wrap-caption animation style1">
                                <h2 class="ss-mega-title">Design Your Next <br>Favourite Wear</h2>
                                <p class="ss-sub-title xs-hide">The outfit that blend elegance and style for your casual wear</p>
                                <div class="ss-btnWrap">
                                    <a class="btn btn-primary" href="shop-grid-view.html">Shop now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--End Home Slideshow-->

templates/web/partials/footer.html
{% load static %}

 <!--Footer-->
 <div class="footer">
    <div class="newsletterbg clearfix">
        <div class="container">
            <form action="#" method="post" class="footer-newsletter">
                <div class="row align-items-center">
                    <div class="col-12 col-sm-12 col-md-6 col-lg-6 mb-3 mb-md-0">
                        <label class="h3 mb-1 clr-none">Sign Up Our Newsletter & Get 10% OFF</label>
                        <p>Sign up to stay in the loop. Receive updates, access to exclusive deals, and more.</p>
                    </div>
                    <div class="col-12 col-sm-12 col-md-6 col-lg-6">
                        <div class="input-group">
                            <input type="email" class="form-control input-group-field newsletter-input" name="email" value="" placeholder="Enter your email address..." required />
                            <button type="submit" class="input-group-btn btn btn-secondary newsletter-submit" name="commit">Subscribe</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="footer-top clearfix">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-12 col-md-3 col-lg-3 footer-links">
                    <h4 class="h4">Informations</h4>
                    <ul>
                        <li><a href="my-account.html">My Account</a></li>
                        <li><a href="aboutus-style1.html">About us</a></li>
                        <li><a href="login.html">Login</a></li>
                        <li><a href="privacy-policy.html">Privacy policy</a></li>
                        <li><a href="#">Terms &amp; condition</a></li>
                    </ul>
                </div>
                <div class="col-12 col-sm-12 col-md-3 col-lg-3 footer-links">
                    <h4 class="h4">Quick Shop</h4>
                    <ul>
                        <li><a href="#">Bags &amp; Accessories</a></li>
                        <li><a href="#">Tools &amp; Parts</a></li>
                        <li><a href="#">Vegetables</a></li>
                        <li><a href="#">Jewelry</a></li>
                        <li><a href="#">Cosmetics</a></li>
                    </ul>
                </div>
                <div class="col-12 col-sm-12 col-md-3 col-lg-3 footer-links">
                    <h4 class="h4">Customer Services</h4>
                    <ul>
                        <li><a href="#">Request Personal Data</a></li>
                        <li><a href="faqs-style1.html">FAQ's</a></li>
                        <li><a href="contact-style1.html">Contact Us</a></li>
                        <li><a href="#">Orders and Returns</a></li>
                        <li><a href="#">Support Center</a></li>
                    </ul>
                </div>
                <div class="col-12 col-sm-12 col-md-3 col-lg-3 footer-contact">
                    <h4 class="h4">Contact Us</h4>
                    <p class="address d-flex"><i class="icon anm anm-map-marker-al pt-1"></i> 55 Gallaxy Enque, 2568 steet, 23568 NY</p>
                    <p class="phone d-flex align-items-center"><i class="icon anm anm-phone-l"></i>  <b class="me-1 d-none">Phone:</b> <a href="tel:401234567890">(+40) 123 456 7890</a></p>
                    <p class="email d-flex align-items-center"><i class="icon anm anm-envelope-l"></i> <b class="me-1 d-none">Email:</b> <a href="mailto:info@example.com">info@example.com</a></p>
                    <ul class="list-inline social-icons mt-3">
                        <li class="list-inline-item"><a href="#" data-bs-toggle="tooltip" data-bs-placement="top" title="Facebook"><i class="icon anm anm-facebook-f"></i></a></li>
                        <li class="list-inline-item"><a href="#" data-bs-toggle="tooltip" data-bs-placement="top" title="Twitter"><i class="icon anm anm-twitter"></i></a></li>
                        <li class="list-inline-item"><a href="#" data-bs-toggle="tooltip" data-bs-placement="top" title="Pinterest"><i class="icon anm anm-pinterest-p"></i></a></li>
                        <li class="list-inline-item"><a href="#" data-bs-toggle="tooltip" data-bs-placement="top" title="Linkedin"><i class="icon anm anm-linkedin-in"></i></a></li>
                        <li class="list-inline-item"><a href="#" data-bs-toggle="tooltip" data-bs-placement="top" title="Instagram"><i class="icon anm anm-instagram"></i></a></li>
                        <li class="list-inline-item"><a href="#" data-bs-toggle="tooltip" data-bs-placement="top" title="Youtube"><i class="icon anm anm-youtube"></i></a></li>
                    </ul>
                </div>
            </div>               
        </div>
    </div>
    <div class="footer-bottom clearfix">
        <div class="container">
            <div class="d-flex-center flex-column justify-content-md-between flex-md-row-reverse">
                <ul class="payment-icons d-flex-center mb-2 mb-md-0">
                    <li><i class="icon anm anm-cc-visa"></i></li>
                    <li><i class="icon anm anm-cc-mastercard"></i></li>
                    <li><i class="icon anm anm-cc-amex"></i></li>
                    <li><i class="icon anm anm-cc-paypal"></i></li>
                    <li><i class="icon anm anm-cc-discover"></i></li>
                    <li><i class="icon anm anm-cc-stripe"></i></li>
                    <li><i class="icon anm anm-cc-jcb"></i></li>
                </ul>
                <div class="copytext">&copy; 2023 Hema. All Rights Reserved.</div>
            </div>
        </div>
    </div>
</div>
<!--End Footer-->

templates/web/partials/header.html
{% load static %}

 <!--Header-->
 <header class="header d-flex align-items-center header-1 header-fixed">
    <div class="container">        
        <div class="row">
            <!--Logo-->
            <div class="logo col-5 col-sm-3 col-md-3 col-lg-2 align-self-center">
                <a class="logoImg" href="{% url 'web:home' %}"><img src="{% static 'web/assets/images/logo.png' %}" alt="Hema Multipurpose Html Template" title="Hema Multipurpose Html Template" width="149" height="39" /></a>
            </div>
            <!--End Logo-->
            <!--Menu-->
            <div class="col-1 col-sm-1 col-md-1 col-lg-8 align-self-center d-menu-col">
                <nav class="navigation" id="AccessibleNav">
                    <ul id="siteNav" class="site-nav medium center">
                        <li class="lvl1">
                            <a  href="{% url 'web:home' %}">Home</a>
                        </li>
                       <li class="lvl1">
                        <a href="#">Categories</a>
                       </li>
                       <li class="lvl1">
                        <a href="#">Products</a>
                       </li>
                       
                    </ul>
                </nav>
            </div>
            <!--End Menu-->
            <!--Right Icon-->
            <div class="col-7 col-sm-9 col-md-9 col-lg-2 align-self-center icons-col text-right">
               
                {% include 'web/partials/search.html' %}
                <!--Account-->
                <div class="account-parent iconset">
                    <div class="account-link" title="Account"><i class="hdr-icon icon anm anm-user-al"></i></div>
                    <div id="accountBox">
                        <div class="customer-links">
                            <ul class="m-0">
                                <li><a href="#"><i class="icon anm anm-sign-in-al"></i>Sign In</a></li>
                                <li><a href="#"><i class="icon anm anm-user-al"></i>Register</a></li>
                                <li><a href="#"><i class="icon anm anm-user-cil"></i>My Account</a></li>
                                <li><a href="#"><i class="icon anm anm-heart-l"></i>Wishlist</a></li>
                                <li><a href="#"><i class="icon anm anm-random-r"></i>Compare</a></li>
                                <li><a href="#"><i class="icon anm anm-sign-out-al"></i>Sign out</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!--End Account-->
                <!--Wishlist-->
                <div class="wishlist-link iconset" title="Wishlist"><a href="#"><i class="hdr-icon icon anm anm-heart-l"></i><span class="wishlist-count">0</span></a></div>
                <!--End Wishlist-->
                <!--Minicart-->
                <div class="header-cart iconset" title="Cart">
                    <a href="#;" class="header-cart btn-minicart clr-none" data-bs-toggle="offcanvas" data-bs-target="#minicart-drawer"><i class="hdr-icon icon anm anm-cart-l"></i><span class="cart-count">2</span></a>
                </div>
                <!--End Minicart-->
                <!--Mobile Toggle-->
                <button type="button" class="iconset pe-0 menu-icon js-mobile-nav-toggle mobile-nav--open d-lg-none" title="Menu"><i class="hdr-icon icon anm anm-times-l"></i><i class="hdr-icon icon anm anm-bars-r"></i></button>
                <!--End Mobile Toggle-->
            </div>
            <!--End Right Icon-->
        </div>
    </div>
</header>
<!--End Header-->

templates/web/partials/top-bar-slider.html
<!--Marquee Text-->
<div class="topbar-slider clearfix">
    <div class="container-fluid">
        <div class="marquee-text">
            <div class="top-info-bar d-flex">
                <div class="flex-item center">
                    <a href="#">
                        <span> <i class="anm anm-worldwide"></i> BUY ONLINE PICK UP IN STORE</span>
                        <span> <i class="anm anm-truck-l"></i> FREE WORLDWIDE SHIPPING ON ALL ORDERS ABOVE $100</span>
                        <span> <i class="anm anm-redo-ar"></i> EXTENDED RETURN UNTIL 30 DAYS</span>
                    </a>
                </div>
                <div class="flex-item center">
                    <a href="#">
                        <span> <i class="anm anm-worldwide"></i> BUY ONLINE PICK UP IN STORE</span>
                        <span> <i class="anm anm-truck-l"></i> FREE WORLDWIDE SHIPPING ON ALL ORDERS ABOVE $100</span>
                        <span> <i class="anm anm-redo-ar"></i> EXTENDED RETURN UNTIL 30 DAYS</span>
                    </a>
                </div>
                <div class="flex-item center">
                    <a href="#">
                        <span> <i class="anm anm-worldwide"></i> BUY ONLINE PICK UP IN STORE</span>
                        <span> <i class="anm anm-truck-l"></i> FREE WORLDWIDE SHIPPING ON ALL ORDERS ABOVE $100</span>
                        <span> <i class="anm anm-redo-ar"></i> EXTENDED RETURN UNTIL 30 DAYS</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End Marquee Text-->